# Generated by Django 3.1.5 on 2021-02-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210129_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customization',
            field=models.TextField(blank=True, default=''),
        ),
    ]
