# Generated by Django 3.1.5 on 2021-02-17 09:03

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210217_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdetailline',
            name='size',
        ),
        migrations.AddField(
            model_name='customdetailline',
            name='raw_size',
            field=models.CharField(choices=[('72', '72'), ('96', '96'), ('32', '32'), ('160', '160'), ('192', '192'), ('240', '240'), ('288', '288'), ('384', '384')], default='160', max_length=3),
        ),
        migrations.AlterField(
            model_name='customdetailline',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AlterField(
            model_name='customdetailline',
            name='font',
            field=models.CharField(choices=[("'Arial', sans-serif", "'Arial', sans-serif"), ("'Clicker Script', cursive", "'Clicker Script', cursive"), ("'Londrina Solid', cursive", "'Londrina Solid', cursive")], default="'Clicker Script', cursive", max_length=60),
        ),
        migrations.AlterField(
            model_name='customdetailline',
            name='stroke_fill',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
