# Generated by Django 3.1.5 on 2021-02-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210217_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customize_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
