# Generated by Django 3.1.5 on 2021-02-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_customize_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdetailline',
            name='font',
            field=models.CharField(choices=[("'Clicker Script', cursive", "'Clicker Script', cursive"), ("'Londrina Solid', cursive", "'Londrina Solid', cursive"), ("'Audiowide', cursive", "'Audiowide', cursive")], default="'Clicker Script', cursive", max_length=60),
        ),
    ]
