# Generated by Django 3.1.5 on 2021-02-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210219_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdetailline',
            name='raw_size',
            field=models.CharField(choices=[('72', '18'), ('96', '24'), ('128', '32'), ('160', '40'), ('192', '48'), ('240', '60'), ('288', '72'), ('336', '84'), ('384', '96')], default='160', max_length=3),
        ),
    ]
