# Generated by Django 3.1.5 on 2021-02-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210221_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='productreviews',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
