# Generated by Django 3.1.5 on 2021-02-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210221_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='comment',
            field=models.CharField(max_length=254),
        ),
    ]
