# Generated by Django 3.1.5 on 2021-02-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210223_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
